flowchart TD
  Maven[pom.xml Maven build]
  OpenAPIGen[OpenAPI Generator]
  SchemaGen[jsonschema2pojo]
  Jar[ConsultingTypeService.jar]
  Docker[Dockerfile]
  Props[application.properties]
  Maria[SPRING_DATASOURCE_URL]
  Mongo[SPRING_DATA_MONGODB_URI]
  Keycloak[JWT issuer and Keycloak URL]
  Tenant[TENANT_SERVICE_API_URL]
  Maven --> OpenAPIGen
  Maven --> SchemaGen
  Maven --> Jar --> Docker
  Props --> Maria
  Props --> Mongo
  Props --> Keycloak
  Props --> Tenant
  Docker -. risk .-> Java11[Java 11 runtime]
  Maven -. target .-> Java21[Java 21 build]
